language: cpp
sudo: required
matrix:
  include:
  - os: linux
    env: COMPILER=g++-6
    addons:
      apt:
        packages:
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
  - os: linux
    env: COMPILER=g++-7
    addons:
      apt:
        packages:
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
  - os: linux
    env: COMPILER=g++-8
    addons:
      apt:
        packages:
        - g++-8
        sources:
        - ubuntu-toolchain-r-test
  - os: linux
    env: COMPILER=clang
    addons:
      apt:
        packages:
        - clang
        sources:
        - ubuntu-toolchain-r-test
        
before_script:
- export CXX="${COMPILER}"
- echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main universe restricted multiverse"
- sudo apt-get update -qq
- sudo apt-get -qq install libqt5widgets5
- sudo apt-get -qq install libboost-dev
script:
- mkdir -p _build && cd _build
- cmake ..
- cmake --build . --config Release -- -j4
- ctest
notifications:
  irc:
    channels:
    - chat.freenode.net#orpg
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'